import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import Header from "./components/Header";
import PageUpButton from "./components/PageUpButton";
import LocalHotel from "./components/LocalHotel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      <body>
        <header>
          <Header/>
        </header>
        <NavBar />
        <LocalHotel />
        <PageUpButton/>
      </body>
    </html>
  );
}
